name: test

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ruff:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - run: echo test2
